--- a/.github/workflows/ruff.yml
+++ b/.github/workflows/ruff.yml
@@ -1,4 +1,3 @@
-# https://beta.ruff.rs
 name: ruff
 on:
   push:
@@ -12,4 +11,4 @@
     steps:
     - uses: actions/checkout@v4
     - run: pip install --user ruff
-    - run: ruff --output-format=github .
+    - run: ruff --output-format=github .